/*
 * Copyright 2010-2024 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.gradle.dsl.abi;

import org.gradle.api.Task;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.tasks.TaskProvider;
import org.jetbrains.kotlin.gradle.tasks.abi.KotlinLegacyAbiCheckTask;
import org.jetbrains.kotlin.gradle.tasks.abi.KotlinLegacyAbiDumpTask;

/**
 * Extension for configuring dumps stored in the old format used in separate [Binary Compatibility Validator plugin](https://github.com/Kotlin/binary-compatibility-validator).
 *
 * Used for smooth migration from it to a new dump format.
 *
 * @since 2.1.20
 */
@AbiValidationDsl
@ExperimentalAbiValidation
public interface AbiValidationLegacyDumpExtension {
    /**
     * Directory with reference dumps which the dump generated for the current code will be compared with by [legacyCheckTaskProvider] task.
     */
    val referenceDumpDir: DirectoryProperty

    /**
     * Provider for the task of generating an actual dumps for the current code.
     *
     * These dumps are saved in the [KotlinLegacyAbiDumpTask.dumpDir] directory and used when comparing with dumps from the [referenceDumpDir] by the [legacyCheckTaskProvider] task.
     */
    val legacyDumpTaskProvider: TaskProvider<KotlinLegacyAbiDumpTask>

    /**
     * Provider for the task of comparing an actual dumps for the current generated by [legacyDumpTaskProvider] code with dumps from [referenceDumpDir].
     *
     * It will drop if any difference is found in the files.
     */
    val legacyCheckTaskProvider: TaskProvider<KotlinLegacyAbiCheckTask>

    /**
     * Overwrite dumps in [referenceDumpDir] directory with the actual dumps from [KotlinLegacyAbiDumpTask.dumpDir] for current code.
     */
    val legacyUpdateTaskProvider: TaskProvider<Task>
}
